---
- name: configure operating system
  hosts: all
  remote_user: ec2-user
  become: yes
  vars:
    chrony_timezone: Europe/Amsterdam
    firewall_services:
      - name: http
      - name: ssh
        proto: tcp
    fail2ban_jail_configuration:
      - section: sshd
        option: enabled
        value: true
      - section: sshd
        option: port
        value: ssh

  pre_tasks:
    - name: set Europe/Amsterdam as timezone
      timezone:
        hwclock: UTC
        name: Europe/Amsterdam

  roles:
    - robertdebock.epel
    - robertdebock.firewall
    - robertdebock.fail2ban
    - unxnn.chrony