---
- name: simple app deployment
  hosts: all
  remote_user: ansible
  become: yes

  tasks:
    - name: install httpd, git
      yum:
        name: httpd,git
        state: present

    - name: start httpd
      service:
          name: httpd
          enabled: yes
          state: started

    - name: deploy version 1 of the app
      git:
        dest: /var/www/html
        repo: https://github.com/wzzrd/automates_webapp.git
        version: v1.0

    - name: make sure permissions are ok
      file:
        path: /var/www/html/index.html
        mode: 0644