---
- name: simple app deployment
  hosts: all
  remote_user: ansible
  become: yes

  tasks:
    - name: install software
      yum:
        name: httpd,git
        state: present

    - name: start apache
      service:
          name: httpd
          enabled: yes
          state: started

    - name: clone app repo
      git:
        dest: /var/www/html
        repo: https://github.com/wzzrd/automates_webapp
        version: v1.0