---
- name: configure operating system
  hosts: all
  remote_user: ansible
  become: yes
  vars:
    chrony_timezone: Europe/Amsterdam

  pre_tasks:
    - name: set Europe/Amsterdam as timezone
      timezone:
        hwclock: UTC
        name: Europe/Amsterdam

  roles:
    - unxnn.chrony