---
- name: create instance(s) on ec2
  hosts: localhost
  remote_user: root
  become: no
  connection: local

  tasks:
    - name: create an instance on ec2
      ec2:
        image: ami-0badcc5b522737046
        instance_type: t2.medium
        key_name: ansible_tower
        assign_public_ip: yes
        wait: yes
        exact_count: "{{ count }}"
        region: eu-central-1
        wait_timeout: 300
        count_tag:
          event: automates2019
        instance_tags:
          event: automates2019
        vpc_subnet_id: subnet-900e39da
        group_id: sg-b2d436da
      register: ec2
      delegate_to: localhost

    - name: show me the ec2 variable
      var: ec2

    - name: wait for instances to come up
      wait_for_connection:
        delay: 30
      loop: "{{ ec2.instances }}"
      delegate_to: "{{ item.public_dns_name }}"
      when: ec.instances|length > 0