---
- name: create instance(s) on gce
  hosts: localhost
  remote_user: root
  gather_facts: no
  vars:
    instance_ip_addresses: []
    network:
      selfLink: projects/ansible-automates-20191211/global/networks/default

  tasks:
    - name: create instance(s) on gce
      gcp_compute_instance:
        auth_kind: serviceaccount
        name: automates2019gce
        project: ansible-automates-20191211
        labels:
          event: "{{ tag }}"
        machine_type: n1-standard-1
        disks:
          - auto_delete: yes
            boot: yes
            initialize_params:
              disk_size_gb: 20
              source_image: projects/rhel-cloud/global/images/rhel-7-v20191121
        network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
        state: present
        status: RUNNING
        zone: europe-west2-a
      register: gce
      delegate_to: localhost

    - name: show me the gce variable
      debug:
        var: gce
        verbosity: 2

    - name: set public_ip fact
      set_fact:
        public_ip: "{{ gce.networkInterfaces[0].accessConfigs[0].natIP }}"

    - name: show me the natIP variable
      debug:
        var: public_ip
        verbosity: 2

    - name: add new hosts to tmpgroup
      add_host:
        name: "{{ public_ip }}"
        groups: tmpgroup

- name: check connectivity
  hosts: tmpgroup
  remote_user: ec2-user
  gather_facts: no

  tasks:
    - name: wait for instances to come up
      wait_for_connection:
        delay: 10