---
- name: create instance(s) on ec2
  hosts: localhost
  gather_facts: no

  tasks:
    - name: create instance(s) on ec2
      ec2:
        image: ami-0badcc5b522737046
        instance_type: t2.medium
        key_name: ansible_tower
        assign_public_ip: yes
        wait: yes
        exact_count: "{{ count }}"
        region: eu-central-1
        wait_timeout: 300
        count_tag:
          event: "{{ tag }}"
        instance_tags:
          event: "{{ tag }}"
        vpc_subnet_id: subnet-900e39da
        group_id: sg-b2d436da
        user_data: "{{ lookup('template', 'cloud-config.txt.j2' }}"
      register: ec2
      delegate_to: localhost

    - name: add new hosts to tmpgroup
      add_host:
        name: "{{ item.public_dns_name }}"
        groups: tmpgroup
      loop: "{{ ec2.instances }}"

    - name: show me the ec2 variable
      debug:
        var: ec2
        verbosity: 2

- name: check connectivity and set-up user
  hosts: tmpgroup
  remote_user: ansible
  become: yes
  gather_facts: no
  vars:
    cloud: aws
    server_role: webserver

  tasks:
    - name: wait for instances to come up
      wait_for_connection:
        delay: 10

    - include_tasks: setup_custom_facts.yml