---
- name: create instance(s) on ec2
  hosts: localhost
  remote_user: root
  gather_facts: no
  vars:
    instance_ip_addresses: []

  tasks:
    - name: create instance(s) on ec2
      ec2:
        image: ami-0badcc5b522737046
        instance_type: t2.medium
        key_name: ansible_tower
        assign_public_ip: yes
        wait: yes
        exact_count: "{{ count }}"
        region: eu-central-1
        wait_timeout: 300
        count_tag:
          event: "{{ tag }}"
        instance_tags:
          event: "{{ tag }}"
        vpc_subnet_id: subnet-900e39da
        group_id: sg-b2d436da
      register: ec2
      delegate_to: localhost

    - name: show me the ec2 variable
      debug:
        var: ec2
        verbosity: 2

    - name: wait for instances to come up
      wait_for_connection:
        delay: 10
      remote_user: ec2-user
      loop: "{{ ec2.instances }}"