---
- name: create instance(s) on gce
  hosts: localhost
  remote_user: root
  gather_facts: no
  vars:
    network:
      selfLink: projects/ansible-automates-20191211/global/networks/default
    ansible_python_interpreter: /var/lib/awx/venv/ansible/bin/python

  tasks:
    - name: create instance(s) on gce
      gcp_compute_instance:
        auth_kind: serviceaccount
        name: automates2019gce
        project: ansible-automates-20191211
        labels:
          event: "{{ tag }}"
        machine_type: n1-standard-1
        disks:
          - auto_delete: yes
            boot: yes
            initialize_params:
              disk_size_gb: 20
              source_image: projects/rhel-cloud/global/images/rhel-7-v20191121
        network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
        state: present
        status: RUNNING
        zone: europe-west2-a
      register: gce
      delegate_to: localhost

    - name: show me the gce variable
      debug:
        var: gce
        verbosity: 2

    - name: set public_ip fact
      set_fact:
        public_ip: "{{ gce.networkInterfaces[0].accessConfigs[0].natIP }}"

    - name: show me the natIP variable
      debug:
        var: public_ip
        verbosity: 2

    - name: add new hosts to tmpgroup
      add_host:
        name: "{{ public_ip }}"
        groups: tmpgroup

- name: check connectivity
  hosts: tmpgroup
  remote_user: mburgerh
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python

  tasks:
    - name: wait for instances to come up
      wait_for_connection:
        delay: 10

    - name: create ansible user
      user:
        name: ansible
        groups: wheel
        append: yes
        uid: 1010
        state: present

    - name: inject ssh key
      authorized_key:
        user: ansible
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCy1QtNy21ILU3OjY0vgGCFYB5EWZLOwCMe4GqTjFfeVDvBgbQzHmf9OHMcoTreUWnPxgZa2frwzFgzamJl978ixWxPKpeNI9qQ1BO9ZBbg5YGVIYrNFFiw0j2B1mOx4u3tn1ntIW3cAJuOmFSI6U6NZy8JRGmkIvxjBzSqPTTUNfDNGtk00XiwrDHD69e0Zn5sX9W7ERf0QsWGK0tlj2YnaOty2MsRia96OgqGO+oqd6FggmIwPIb+2S0RghQLSRLyWFMKY68zZwugSLkl9r/TSrHPgJjGMWaIX1LyO8SbGrLToL7Cg0ptQrhosz1T2+zcdc+Z6fppTB2lF3cvF92b root@tower.ibm.nontoonyt.com"
        state: present

    - name: change sudoers file, uncomment nopasswd line for wheel
      lineinfile:
        dest: /etc/sudoers
        regexp: '^#\s*\%wheel\s*ALL=\(ALL\)\s*NOPASSWD:\s*ALL.*$'
        line: '%wheel   ALL=(ALL)       NOPASSWD: ALL'

    - name: change sudoers file, comment out plain wheel line
      lineinfile:
        dest: /etc/sudoers
        regexp: '^\%wheel\s*ALL=\(ALL\)\s*ALL.*$'
        line: '#%wheel   ALL=(ALL)       ALL'
