---
- name: create instance(s) on gce
  hosts: localhost
  remote_user: root
  vars:
    instance_ip_addresses: []

  tasks:
    - name: create instance template
      gce_compute_instance_template:
        auth_kind: serviceaccount
        name: automates2019template
        project: ansible-automates-20191211 
        labels:
          event: "{{ tag }}"
        machine_type: n1-standard-1
        state: present
        status: RUNNING
        zone: europe-west4-a
      register: instancetemplate
      delegate_to: localhost

