---
- name: create instance(s) on gce
  hosts: localhost
  remote_user: root
  gather_facts: no
  vars:
    instance_ip_addresses: []
    network:
      selfLink: projects/ansible-automates-20191211/regions/europe-west4/subnetworks/default

  tasks:
    - name: create instance(s) on gce
      gcp_compute_instance:
        auth_kind: serviceaccount
        name: automates2019template
        project: ansible-automates-20191211
        labels:
          event: "{{ tag }}"
        machine_type: n1-standard-1
        network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
        state: present
        status: RUNNING
        zone: europe-west4-a
      register: gce
      delegate_to: localhost

    - name: show me the gce variable
      debug:
        var: ec2
        verbosity: 2