---
- name: create instance(s) on ec2
  hosts: localhost
  remote_user: root
  become: no
  connection: local

  tasks:
    - name: create an instance on ec2
      ec2:
        image: ami-0badcc5b522737046
        instance_type: t2.medium
        id: automates
        state: "{{ state }}"
        key_name: ansible_tower
        assign_public_ip: yes
        wait: yes
        count: "{{ count }}"
        region: eu-central-1
        wait_timeout: 300
        instance_tags: 
          event: automates2019
      register: ec2

    - name: wait for instances to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 30
      loop: "{{ ec2.instances }}"