---
services: docker

env:
  - distro: centos7
  - distro: centos6
  - distro: ubuntu1604
  - distro: ubuntu1404
  - distro: ubuntu1204

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Make sure haproxy is installed.
  - 'docker exec --tty ${container_id} env TERM=xterm haproxy -v'

  # Make sure stats page is available and accessible.
  - 'docker exec --tty ${container_id} env TERM=xterm curl --user user:pass localhost:7777 | grep "Statistics Report"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
